/**
 * weekly-charles.tsx — Monday morning letter from Charles to the user.
 *
 * AI-generated personal reflection / reading encouragement.
 */

import { Section, Text, Button } from "@react-email/components";
import EmailWrapper from "./email-wrapper";

interface WeeklyCharlesEmailProps {
  recipientName: string | null;
  letterBody: string;       // Generated by Charles AI
  readingPlanSummary?: string; // e.g. "You're in week 3 of Romans"
  appUrl: string;
}

const s = {
  from: { fontSize: "12px", letterSpacing: "0.12em", textTransform: "uppercase" as const, color: "#C4A040", marginBottom: "20px" },
  letter: {
    fontSize: "16px",
    color: "#D4C9BC",
    lineHeight: "1.85",
    fontFamily: "'Georgia', serif",
    whiteSpace: "pre-wrap" as const,
    marginBottom: "24px",
  },
  plan: {
    fontSize: "13px",
    color: "#C4A040",
    borderLeft: "2px solid #C4A040",
    paddingLeft: "12px",
    marginBottom: "24px",
  },
  sig: { fontSize: "15px", color: "#B8AFA4", fontStyle: "italic" },
  btn: {
    backgroundColor: "transparent",
    color: "#C4A040",
    borderRadius: "6px",
    padding: "10px 20px",
    fontSize: "13px",
    fontWeight: "600",
    textDecoration: "none",
    display: "inline-block",
    border: "1px solid #C4A040",
    marginTop: "20px",
  },
};

export default function WeeklyCharlesEmail({
  recipientName,
  letterBody,
  readingPlanSummary,
  appUrl,
}: WeeklyCharlesEmailProps) {
  const name = recipientName ?? "Friend";
  const preview = `A letter from Charles — good morning, ${name}`;

  return (
    <EmailWrapper preview={preview}>
      <Section>
        <Text style={s.from}>From Charles · This week</Text>
        <Text style={s.letter}>{letterBody}</Text>
        {readingPlanSummary && (
          <Text style={s.plan}>{readingPlanSummary}</Text>
        )}
        <Text style={s.sig}>— Charles</Text>
        <Button href={appUrl} style={s.btn}>
          Open Bible Study
        </Button>
      </Section>
    </EmailWrapper>
  );
}
