/**
 * database.ts — Supabase database type definitions
 *
 * This file is auto-generated by: supabase gen types typescript --project-id <id>
 * Run this command after connecting your Supabase project.
 *
 * DO NOT EDIT MANUALLY.
 *
 * To regenerate:
 *   npx supabase gen types typescript --project-id YOUR_PROJECT_ID > src/types/database.ts
 *
 * Or with the Supabase CLI:
 *   supabase gen types typescript --local > src/types/database.ts
 */

// Placeholder until `supabase gen types` is run against a live schema.
// Replace this entire file with the generated output.
export type Database = {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}

export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']

export type TablesInsert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert']

export type TablesUpdate<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update']
